BEGIN;

ALTER TABLE inventario
  ADD COLUMN IF NOT EXISTS numero_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS data_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS periodicita VARCHAR(100);

ALTER TABLE inventario_libri
  ADD COLUMN IF NOT EXISTS numero_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS data_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS periodicita VARCHAR(100);

ALTER TABLE inventario_tesi
  ADD COLUMN IF NOT EXISTS numero_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS data_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS periodicita VARCHAR(100);

ALTER TABLE inventario_cataloghi
  ADD COLUMN IF NOT EXISTS numero_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS data_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS periodicita VARCHAR(100);

ALTER TABLE inventario_riviste
  ADD COLUMN IF NOT EXISTS numero_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS data_rivista VARCHAR(255),
  ADD COLUMN IF NOT EXISTS periodicita VARCHAR(100);

COMMIT;
